### ISSUE TITLE
Random prompts

### ISSUE THREAD

**Issue by danzelus** [some9000/StylePile#16]
Make it possible to specify not one word but several in a line. The "cat" works, but the "big cat" does not
------------------------------
By the way, this is a very useful feature, I use it all the time. I would like there to be not one menu but several, or just to be able to change in different places.
For example, "a big cat in a hat on the couch", "[R] a cat in [Z] on [Y]"

**Comment by some9000** [comment]
Is this from the current version or the beta version? Because Beta (https://github.com/some9000/StylePile/tree/Beta) has this at the moment (each of those windows take multiple lines (I have tested up to 300):
![image](https://user-images.githubusercontent.com/17021558/200592789-2a6af1e5-8735-4513-bf5b-de84d8ef3b23.png)
If you already meant Beta, then a little more information could help me get the idea better.

**Comment by danzelus** [comment]
Sry, i didn't know about beta, sry
Yes beta is what I was talking about 🙂

**Comment by some9000** [comment]
Cool. That function is really useful indeed. Can create a great variety of things really quickly.
