### ISSUE TITLE
Feature Request - Artist Category 

### ISSUE THREAD

**Issue by Kylescher1** [some9000/StylePile#2]
Not sure if this is the best place to contact you, but another tab with artist selection would be great!

**Comment by some9000** [comment]
Yeah, this is a good place for suggestions.
Have been thinking about that, but since there are that many artists I want to think of some way to group them or such. Perhaps by most common themes and looks in their work. It is certainly under consideration.

**Comment by Kylescher1** [comment]
I disagree but at the same time see your point. Each artist can have a unique style.

**Comment by some9000** [comment]
I will likely implement that anyway. Since the view selection does nearly nothing. I did 500+ test images and whatever you enter about view, unless it is something extreme, like macro or wide angle it completely ignores that. So adding some artist lists might be a better idea.

Or were you implying a straight up 150 artist (or, ok, 20 top ones) dropdown?

**Comment by Kylescher1** [comment]
To be honest I am not sure the best way to go about it. Each artist can be unique but at the same time falls into a category

**Comment by some9000** [comment]
For now I have added these artists with this image preview into incoming next version:
![Artists](https://user-images.githubusercontent.com/17021558/197756706-4466f6bc-5da3-4a5b-a6a1-162c0638568f.png)
If you feel like someone should absolutely be included do share.

**Comment by Kylescher1** [comment]
Great first step!
