### ISSUE TITLE
Specified seed not incrementing with batch size

### ISSUE THREAD

**Issue by scytalezero** [some9000/StylePile#35]
First off, I really love StylePile! It's great for a beginner like me still trying to figure things out and has some powerful advanced features. 

One thing I did notice - I'm using the [X] replacement a lot to see how different wordings affect my output. I like to have the same seed used for each of my [X]but a few examples of each. Reading the doc, it seems like if I have 4 [X] prompts, a batch size of 4, and a specified seed, I should see the first 4 images use the first row in the [X] box (this is indeed what happens) but each image incrementing the seed by 1 until it hits image 5 at which point it resets to the specified seed taking the next prompt from [X]. 

Instead I see 4 identical images (same seed) for X[1], then 4 identical images for X[2], etc. Example:

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/704908/206234863-71298188-985f-4459-a724-0292e3e22e45.png">

My settings:

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/704908/206235044-206b2785-54f0-4168-8452-9d7b833e3367.png">

**Comment by some9000** [comment]
Always nice to hear positive feedback. It looks like you may have been using an older version at the time of writing this. But I have made a small update anyway just now so make sure to update. Things should look like this to have multiple examples per prompt (now there is a checkbox to select if the seed grows or not):
![image](https://user-images.githubusercontent.com/17021558/206380505-ff646ae6-9d15-4692-b8b2-528f0464faa0.png)
From my testing of similar idea it looked like "By Artist XXX" was the best way to define them. So that's what the dropdowns do.

**Comment by scytalezero** [comment]
Awesome! Yep, I was behind and it's working exactly like I would expect now. Also thank you for the "by artist ..." tip 👍
