### ISSUE TITLE
View appears to be missing a leading comma in the prompt...

### ISSUE THREAD

**Issue by kalebwyman** [some9000/StylePile#5]
@some9000 

When I inspect a prompt using StylePile > View, it appears to be missing a leading comma ", " as a prefix before the View string, so it is merging its text with the previous text prompt.

For example, if I choose:
Colors: Chaotic
View: Birds-eye view

The text prompt becomes this:
(painterly)chaotic colors(birds-eye view),distant

Note the missing ", " string between colors and (bird-eye view) above.

The text prompt should be this:
(painterly)chaotic colors, (birds-eye view),distant

**Comment by some9000** [comment]
Indeed. Thanks for the heads up. But since then I have already massively changed the way things work and the keywords, etc. Gaining more understanding of how the generation works and making literally hundreds of test images. Next version will be somewhat different, but I will go through the keywords to check correctness.
