### ISSUE TITLE
Export/import settings?

### ISSUE THREAD

**Issue by nightgolfer** [some9000/StylePile#50]
Loving it! Makes everything so much easier, and the ability to look up styles and artists is fantastic.

Any chance of being able to export/import SP settings? I've got a nice setup right now, but I'm on a rented server and when I spin it up again tomorrow all my settings will have been reset. It would be really nice to be able to import my SP settings from this session tomorrow.

Even if it's just text I can copy/paste into a prompt that would be great, I can keep a local list in Obsidian of different prompts that I like and import them when needed.

**Comment by some9000** [comment]
Hi! Glad to hear you like it.
I have actually been trying to get that sort of functionality in for about two weeks now when there is some time. But my Python skills are terrible. So made a topic asking for some help from knowledgeable people. Hopefully that can be done, since it would be great to make complex presets with plenty of keywords to easily make a bunch of artwork quickly and then come back and make more.

**Comment by nightgolfer** [comment]
That's great news! I hope it works out. Sadly, I have zero Python skills so can't be of any help in that department, but do let me know if I can help test or give feedback =)

**Comment by some9000** [comment]
A version of this will be added to the next version - saving and loading string prompt presets (including all the additional X,Y,A,B... variables).

**Comment by nightgolfer** [comment]
Fantastic, thank you!!! =D

**Comment by some9000** [comment]
If you are feeling a little brave (don't worry, it is stable, just with some mild rough edges) you can try the 2.1 version from here: https://github.com/some9000/StylePile/tree/Error-hunting

Just make sure to fully replace the previous one with all the folders, etc.

**Comment by nightgolfer** [comment]
Thank you, I'll give that a try tomorrow =D
